{{- $serviceDomain := "local.zeppelin-project.org:8080" }}
{{- if .Values.ingress.hosts }}
{{- $firstHost := index .Values.ingress.hosts 0 }}
{{- $serviceDomain = $firstHost.host }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zeppelin.fullname" . }}-server
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
data:
  SERVICE_DOMAIN: {{ $serviceDomain }}
  ZEPPELIN_K8S_SPARK_CONTAINER_IMAGE: {{ .Values.image.spark.repository }}:{{ .Values.image.spark.tag }}
  ZEPPELIN_K8S_CONTAINER_IMAGE: {{ .Values.image.server.repository }}:{{ .Values.image.server.tag | default .Chart.AppVersion }}
  ZEPPELIN_HOME: /opt/zeppelin
  ZEPPELIN_SERVER_RPC_PORTRANGE: 12320:12320
  # default value of 'master' property for spark interpreter.
  SPARK_MASTER: k8s://https://kubernetes.default.svc
  # default value of 'SPARK_HOME' property for spark interpreter.
  SPARK_HOME: /spark
