kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeppelin.fullname" . }}-server
subjects:
- kind: ServiceAccount
  name: {{ include "zeppelin.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "zeppelin.fullname" . }}-server
  apiGroup: rbac.authorization.k8s.io
