apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeppelin.fullname" . }}-server
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.rpc.servicePort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "zeppelin.selectorLabels" . | nindent 4 }}
